version: '3'

services:
  db:
    container_name: db
    image: postgres:13.0-alpine
    volumes:
      - data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=jaspercyan
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  redis:
    image: redis
    container_name: redis
  
  api:
    container_name: api
    image: api
    build: 
      context: ./fliprLicensingApi
      dockerfile: Dockerfile.django
    volumes:
      - ./fliprLicensingApi:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    env_file:
      - ./fliprLicensingApi/.env

  celery-worker:
    restart: always
    container_name: celery-worker
    image: api-celery-worker
    build: 
      context: ./fliprLicensingApi
      dockerfile: Dockerfile.celery
    command: celery -A fliprLicensingApi worker -l DEBUG
    volumes:
      - ./fliprLicensingApi:/app
    depends_on:
      - db
      - redis
      - api

  celery-beat:
    container_name: celery-beat
    image: api-celery-beat
    build: 
      context: ./fliprLicensingApi
      dockerfile: Dockerfile.celery
    volumes:
      - ./fliprLicensingApi:/app
    depends_on:
      - redis
      - db

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./nginx/certbot/conf:/etc/letsencrypt
    - ./nginx/certbot/logs:/var/log/letsencrypt
    - ./nginx/certbot/data:/usr/share/nginx/html/letsencrypt
    ports:
    - 80:80
    - 443:443
    depends_on:
      # - prometheus
      - api

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - 9090:9090
    depends_on:
      - api

  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    restart: 'always'
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=rahulranjan25.RR@gmail.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   ports:
  #     - 5050:80

volumes:
  data:
  grafana: