version: '3'

services:
  api:
    container_name: api
    build: 
      context: ./fliprLicensingApi
      dockerfile: Dockerfile
    volumes:
      - ./fliprLicensingApi/static:/static
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./fliprLicensingApi/.env

  db:
    container_name: postgres-db
    image: postgres:13.0-alpine
    volumes:
      - data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=jaspercyan
      - POSTGRES_USER=postgres
      - POSTGRES_DB=notesdatabase
    ports:
      - 5432:5432

  nginx:
    image: nginx
    restart: always
    volumes:
    - ./static:/static
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./nginx/certbot/conf:/etc/letsencrypt
    - ./nginx/certbot/logs:/var/log/letsencrypt
    - ./nginx/certbot/data:/usr/share/nginx/html/letsencrypt
    ports:
    - 80:80
    - 443:443
    depends_on:
      - prometheus
      - api

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - 9090:9090
    depends_on:
      - api

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: 'always'
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

volumes:
  data:
  grafana: