# Generated by Django 4.2.1 on 2023-05-11 10:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licenses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(editable=False, max_length=1024, unique=True)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('USER_SCOPE_MISMATCH', 'Incorrect Email')], default='VALID', max_length=255)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
        ),
    ]
