# Generated by Django 4.2.1 on 2023-05-12 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_rename_licenses_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='private_key',
            field=models.CharField(editable=False, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='public_key',
            field=models.CharField(editable=False, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
