# Generated by Django 4.2.1 on 2023-05-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_license_private_key_license_public_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('VALID', 'Valid'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('USER_SCOPE_MISMATCH', 'Incorrect Email'), ('INVALID', 'Not Found')], default='VALID', max_length=255),
        ),
    ]
