# Generated by Django 4.2.1 on 2023-05-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_license_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('VALID', 'Valid'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], default='VALID', max_length=255),
        ),
    ]
