global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    metrics_path: /metrics
    static_configs:
      - targets:
        - web:8000

scrape_configs:
  - job_name: "api"
    metrics_path: /api/metrics
    static_configs:
      - targets:
        - web:8000