FROM python:3-slim-buster
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
WORKDIR /app
ADD . /app
RUN apt-get update
RUN pip install --upgrade pip
COPY ./requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt
# COPY . /app
# RUN apt-get -y install curl awscli
ENTRYPOINT [ "bash", "script.sh" ]
# HEALTHCHECK CMD curl --fail http://localhost:8000/api || exit 1
