# Generated by Django 4.2.1 on 2023-05-19 11:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(editable=False, max_length=1024, unique=True)),
                ('public_key', models.CharField(editable=False, max_length=2048, null=True)),
                ('private_key', models.CharField(editable=False, max_length=2048, null=True)),
                ('status', models.CharField(default='VALID', max_length=255)),
                ('validUpto', models.DateTimeField(default=datetime.datetime(2024, 5, 18, 11, 25, 42, 496201, tzinfo=datetime.timezone.utc))),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
