# Generated by Django 4.2.1 on 2023-05-19 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_license_validupto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='validUpto',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 18, 11, 29, 20, 979004, tzinfo=datetime.timezone.utc)),
        ),
    ]
