# Generated by Django 4.2.1 on 2023-05-19 18:18

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_license_validupto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('validity', models.DurationField(blank=True, choices=[(datetime.timedelta(days=1), 'Day'), (datetime.timedelta(days=7), 'Week'), (datetime.timedelta(days=28), 'Month')], null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='license',
            name='validUpto',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 18, 18, 18, 40, 937542, tzinfo=datetime.timezone.utc)),
        ),
    ]
