# Generated by Django 4.2.1 on 2023-05-19 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_policy_alter_license_validupto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='validUpto',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 18, 18, 37, 2, 444152, tzinfo=datetime.timezone.utc)),
        ),
    ]
