# Generated by Django 4.2.1 on 2023-05-19 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_license_validupto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name_plural': 'Policies'},
        ),
        migrations.AlterField(
            model_name='license',
            name='validUpto',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 18, 18, 52, 21, 809137, tzinfo=datetime.timezone.utc)),
        ),
    ]
