# Generated by Django 4.2.1 on 2023-05-19 19:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_policy_options_alter_license_validupto'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.policy'),
        ),
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('VALID', 'Valid'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], default='VALID', max_length=255),
        ),
        migrations.AlterField(
            model_name='license',
            name='validUpto',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='validity',
            field=models.DurationField(blank=True, choices=[(datetime.timedelta(seconds=60), 'Minute'), (datetime.timedelta(days=1), 'Day'), (datetime.timedelta(days=7), 'Week'), (datetime.timedelta(days=28), 'Month')], null=True),
        ),
    ]
