# Generated by Django 4.2.1 on 2023-05-20 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_license_policy_alter_license_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='validity',
            field=models.DurationField(blank=True, choices=[(datetime.timedelta(seconds=120), 'Minute'), (datetime.timedelta(days=1), 'Day'), (datetime.timedelta(days=7), 'Week'), (datetime.timedelta(days=28), 'Month')], null=True),
        ),
    ]
